# Generated by Django 6.0 on 2025-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('tempo_servico', models.IntegerField(help_text='Tempo de serviço em anos')),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
